name: Daily Data Update

on:
  schedule:
    - cron: "0 6 * * *" # Runs every day at 6 AM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update currencies
        run: python scripts/update_currencies.py

      - name: Update events
        run: python scripts/update_events.py

      - name: Run OLS regression
        run: python scripts/run_ols_regression.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/ # <-- commit everything under data/
          git commit -m "Daily update: data + OLS regression" || echo "No changes to commit"
          git push
