name: Update Historical Events

on:
  schedule:
    - cron: "0 6 * * *"   # Runs every day at 06:00 UTC
  workflow_dispatch:       # Manual trigger

permissions:
  contents: write   # 👈 allow pushing changes

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install pandas requests beautifulsoup4 pyarrow fastparquet

    - name: Run script
      run: python scripts/update_historical_events.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add data/events/*.parquet
        git commit -m "Update GDELT events $(date -u)" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
