name: Update Historical Events

on:
  schedule:
    - cron: "0 6 * * *"   # Runs every day at 06:00 UTC
  workflow_dispatch:       # Also allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install pandas requests beautifulsoup4 pyarrow fastparquet

    - name: Run script
      run: python gdelt_events.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/events/*.parquet
        git commit -m "Update GDELT events $(date -u)"
        git push
