name: Daily Dataset Update

on:
  schedule:
    - cron: "0 6 * * *"   # runs every day at 6 AM UTC
  workflow_dispatch:       # manual trigger option

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run event updater
        run: python scripts/historical_events.py

      - name: Run currency updater
        run: python scripts/historical_currencies.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/ checkpointer.txt
          git commit -m "Auto update dataset $(date)" || echo "No changes"
          git push
