name: Update Historical Events and Currencies

on:
  schedule:
    - cron: "0 6 * * *"   # Runs every day at 06:00 UTC
  workflow_dispatch:       # Manual trigger

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0   # fetch full history to allow pull/rebase

    - name: Pull latest changes to avoid conflicts
      run: |
        git fetch origin main
        git reset --hard origin/main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install pandas requests beautifulsoup4 pyarrow fastparquet yfinance openpyxl

    - name: Run update scripts
      run: |
        # Skip update if data folders or Excel missing
        if [ ! -d "data/events" ]; then mkdir -p data/events; fi
        if [ ! -d "data/currencies" ]; then mkdir -p data/currencies; fi
        python scripts/update_historical_events.py
        python scripts/update_historical_currencies.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add data/events/*.parquet
