name: Daily Data Update

on:
  schedule:
    - cron: "0 6 * * *" # Every day 6 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed for pull+rebase

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update currencies
        run: python scripts/update_historical_currencies.py

      - name: Update events
        run: python scripts/update_historical_events.py

      - name: List data files (debug)
        run: |
          echo "---- data/events ----"
          ls -lh data/events || true
          echo "---- data/currencies ----"
          ls -lh data/currencies || true
          echo "---- data/spike_dip_events.csv ----"
          ls -lh data/spike_dip_events.csv || true

      # 1️⃣ Commit + push to main
      - name: Commit and push to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "Daily update: currencies, events, spikes/dips" || echo "No changes to commit"
          git pull --rebase origin main || true
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main || echo "Push to main failed"

      # 2️⃣ Commit + push to fallback branch
      - name: Commit and push to data-storage branch
        if: always() # run even if main push fails
        run: |
          git checkout -B data-storage
          git add data/
          git commit -m "Daily update backup: parquet storage" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git data-storage --force || echo "Push to data-storage failed"

      # 3️⃣ Upload artifacts
      - name: Upload Parquet files as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: parquet-files
          path: |
            data/events/**/*.parquet
            data/currencies/**/*.parquet
            data/spike_dip_events.csv
